[package]
name = "maze"
version = "0.1.0"
edition = "2021"
author = "Sudesh Subedi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
rand = "0.8.5"
colored = "2.0.0"